version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: club_social-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: club_social
    ports:
      - '5430:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - club_social_network

  adminer:
    image: adminer
    container_name: adminer_cs_db
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - '8080:8080'
    networks:
      - club_social_network

networks:
  club_social_network:
    driver: bridge

volumes:
  postgres_data:
